"use client";

import { useEffect, useRef, useState } from "react";

type Props = {
  /** The Mermaid diagram source */
  chart: string;
  /** Optional caption shown beneath the diagram */
  caption?: string;
};

/**
 * Client-side Mermaid renderer.
 *
 * Lazy-loads the mermaid package only on pages that use it, and themes it
 * to match the editorial palette (terracotta accent, paper bg, ink stroke,
 * Fraunces serif for node labels).
 */
export function Mermaid({ chart, caption }: Props) {
  const ref = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>("");
  const [error, setError] = useState<string | null>(null);
  // Unique-ish id so multiple diagrams on a page don't collide.
  const idRef = useRef<string>(
    `mmd-${Math.random().toString(36).slice(2, 10)}`,
  );

  useEffect(() => {
    let cancelled = false;

    (async () => {
      try {
        const mermaid = (await import("mermaid")).default;
        mermaid.initialize({
          startOnLoad: false,
          theme: "base",
          fontFamily: "var(--font-fraunces), Georgia, serif",
          themeVariables: {
            // Nodes: warm sand — clearly visible against the paper background
            background: "#faf7f0",
            primaryColor: "#e8dfd0",
            primaryTextColor: "#1c1a16",
            primaryBorderColor: "#6b5040",
            mainBkg: "#e8dfd0",
            // Edges and labels
            lineColor: "#6b5040",
            edgeLabelBackground: "#faf7f0",
            // Subgraphs: one shade darker than nodes
            secondaryColor: "#ddd4c2",
            tertiaryColor: "#f0ebe0",
            clusterBkg: "#ddd4c2",
            clusterBorder: "#6b5040",
            // Terracotta accent (use :::accent after a node id in the chart)
            cScale0: "#b5482a",
          },
          flowchart: {
            htmlLabels: true,
            curve: "basis",
            padding: 16,
            nodeSpacing: 40,
            rankSpacing: 50,
          },
          sequence: { actorMargin: 50 },
        });

        const { svg } = await mermaid.render(idRef.current, chart);
        if (!cancelled) setSvg(svg);
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : String(err));
        }
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [chart]);

  // After the SVG mounts, animate each stroked element drawing in when the
  // figure enters the viewport. Respects prefers-reduced-motion.
  useEffect(() => {
    if (!svg) return;
    const fig = ref.current;
    if (!fig) return;
    if (typeof window === "undefined") return;
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

    const strokes = Array.from(
      fig.querySelectorAll<SVGGeometryElement>(
        "path, line, polyline, polygon",
      ),
    );
    if (strokes.length === 0) return;

    // Pre-hide every stroked element. CSS handles the transition timing.
    strokes.forEach((el, i) => {
      let length = 0;
      try {
        length = el.getTotalLength();
      } catch {
        // Some browsers throw on filled-only elements; just skip those.
        return;
      }
      if (length === 0) return;
      el.style.strokeDasharray = String(length);
      el.style.strokeDashoffset = String(length);
      el.style.transitionDelay = `${i * 120}ms`;
    });

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          strokes.forEach((el) => {
            el.style.strokeDashoffset = "0";
          });
          observer.disconnect();
        }
      },
      { rootMargin: "0px 0px -10% 0px" },
    );

    observer.observe(fig);
    return () => observer.disconnect();
  }, [svg]);

  if (error) {
    return (
      <div className="my-8 p-4 border border-terracotta/40 text-sm text-terracotta">
        Mermaid render failed: {error}
      </div>
    );
  }

  return (
    <figure className="my-10 reveal-mermaid">
      <div
        ref={ref}
        className="overflow-x-auto [&_svg]:mx-auto [&_svg]:max-w-full [&_svg]:h-auto"
        // svg is generated by mermaid which we trust (no user input)
        dangerouslySetInnerHTML={{ __html: svg }}
      />
      {caption && (
        <figcaption className="mt-3 text-center text-sm italic font-display text-ink-muted">
          {caption}
        </figcaption>
      )}
    </figure>
  );
}
